# Generated by Django 4.0.3 on 2022-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenumber',
            name='daily',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='homenumber',
            name='monthly',
            field=models.IntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name='homenumber',
            name='packs',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='homenumber',
            name='partners',
            field=models.IntegerField(default=5),
        ),
    ]
