# Generated by Django 4.0.3 on 2022-04-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.FloatField()),
                ('paid_status', models.BooleanField(default=False)),
                ('order_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cat_imgs/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(default='...')),
                ('image', models.ImageField(upload_to='GFXPack_Images/')),
                ('category', models.CharField(choices=[('UGT', 'User GFX Pack Thumbnail'), ('UGB', 'User GFX Pack Banner'), ('UGI', 'User GFX Pack Intro'), ('UGO', 'User GFX Pack Outro'), ('UGP', 'User GFX Pack Poster'), ('UGR', 'User GFX Pack Render'), ('UGG', 'User GFX Pack GFX Materials'), ('--', '------'), ('UDT', 'User Designs Thumbnail'), ('UDB', 'User Designs Banner'), ('UDI', 'User Designs Intro'), ('UDO', 'User Designs Outro'), ('UDP', 'User Designs Poster'), ('UDOth', 'User Designs Other'), ('NT', 'Nawab Designs Thumbnail'), ('NB', 'Nawab Designs Banner'), ('NI', 'Nawab Designs Intro'), ('NO', 'Nawab Designs Outro'), ('NP', 'Nawab Designs Poster'), ('NOth', 'Nawab Designs Other'), ('PPT', 'Paid Packs Thumbnail'), ('PPB', 'Paid Packs Banner'), ('PPI', 'Paid Packs Intro'), ('PPO', 'Paid Packs Outro'), ('PPP', 'Paid Packs Poster'), ('PPR', 'Paid Packs Render'), ('PPG', 'Paid Packs GFX Materials'), ('FPT', 'Free Packs Thumbnail'), ('FPB', 'Free Packs Banner'), ('FPI', 'Free Packs Intro'), ('FPO', 'Free Packs Outro'), ('FPP', 'Free Packs Poster'), ('FPR', 'Free Packs Render'), ('FPG', 'Free Packs GFX Materials')], default='--', max_length=90)),
                ('slug', models.CharField(max_length=400, null=True)),
                ('order_link', models.CharField(blank=True, max_length=999)),
                ('download_link', models.CharField(blank=True, max_length=999)),
                ('buy_link', models.CharField(blank=True, max_length=999)),
                ('status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sp', models.IntegerField(default=0)),
                ('dp', models.IntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='YTPACKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(default='...')),
                ('image', models.ImageField(upload_to='GFXPack_Images/')),
                ('category', models.CharField(choices=[('SST', 'SS Graphics Thumbnail'), ('NEP', 'Nawab Editz Poster'), ('SSP', 'SS Graphics Poster'), ('ABI', 'Aquas Brain Intro'), ('SSR', 'SS Graphics Render'), ('ABO', 'Aquas Brain Outro'), ('SSI', 'SS Graphics Intro'), ('ABB', 'Aquas Brain Banner'), ('AGP', 'Arpit Graphiz Poster'), ('AGG', 'Arpit Graphiz GFX Materials'), ('SSO', 'SS Graphics Outro'), ('ABP', 'Aquas Brain Poster'), ('NEG', 'Nawab Editz GFX Materials'), ('AGB', 'Arpit Graphiz Banner'), ('ABR', 'Aquas Brain Render'), ('NET', 'Nawab Editz Thumbnail'), ('SSB', 'SS Graphics Banner'), ('NEI', 'Nawab Editz Intro'), ('AGO', 'Arpit Graphiz Outro'), ('NEB', 'Nawab Editz Banner'), ('AGR', 'Arpit Graphiz Render'), ('NEO', 'Nawab Editz Outro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('SSG', 'SS Graphics GFX Materials'), ('--', '------'), ('ABT', 'Aquas Brain Thumbnail'), ('ABG', 'Aquas Brain GFX Materials'), ('AGI', 'Arpit Graphiz Intro'), ('NER', 'Nawab Editz Render')], default='--', max_length=90)),
                ('download_link', models.CharField(blank=True, max_length=999)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'title',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfx.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfx.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfx.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='title',
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=150)),
                ('item', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfx.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
