# Generated by Django 4.0.3 on 2022-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('SST', 'SS Graphics Thumbnail'), ('SSR', 'SS Graphics Render'), ('NEO', 'Nawab Editz Outro'), ('AGO', 'Arpit Graphiz Outro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('SSO', 'SS Graphics Outro'), ('ABP', 'Aquas Brain Poster'), ('NEG', 'Nawab Editz GFX Materials'), ('NEI', 'Nawab Editz Intro'), ('NER', 'Nawab Editz Render'), ('ABO', 'Aquas Brain Outro'), ('ABI', 'Aquas Brain Intro'), ('ABB', 'Aquas Brain Banner'), ('AGR', 'Arpit Graphiz Render'), ('--', '------'), ('SSG', 'SS Graphics GFX Materials'), ('NET', 'Nawab Editz Thumbnail'), ('NEB', 'Nawab Editz Banner'), ('NEP', 'Nawab Editz Poster'), ('AGB', 'Arpit Graphiz Banner'), ('AGG', 'Arpit Graphiz GFX Materials'), ('SSI', 'SS Graphics Intro'), ('SSB', 'SS Graphics Banner'), ('AGI', 'Arpit Graphiz Intro'), ('ABR', 'Aquas Brain Render'), ('SSP', 'SS Graphics Poster'), ('AGP', 'Arpit Graphiz Poster'), ('ABG', 'Aquas Brain GFX Materials'), ('ABT', 'Aquas Brain Thumbnail')], default='--', max_length=90),
        ),
    ]
