# Generated by Django 4.0.3 on 2022-04-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersname',
            name='slug',
        ),
    ]
