# Generated by Django 4.0.3 on 2022-04-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sp',
            field=models.IntegerField(null=True),
        ),
    ]
