# Generated by Django 4.0.3 on 2022-04-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0002_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gfx.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('AGO', 'Arpit Graphiz Outro'), ('AGP', 'Arpit Graphiz Poster'), ('NEO', 'Nawab Editz Outro'), ('ABI', 'Aquas Brain Intro'), ('AGI', 'Arpit Graphiz Intro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('NET', 'Nawab Editz Thumbnail'), ('SSB', 'SS Graphics Banner'), ('SSP', 'SS Graphics Poster'), ('SSO', 'SS Graphics Outro'), ('SSR', 'SS Graphics Render'), ('NEB', 'Nawab Editz Banner'), ('NER', 'Nawab Editz Render'), ('AGR', 'Arpit Graphiz Render'), ('ABB', 'Aquas Brain Banner'), ('AGG', 'Arpit Graphiz GFX Materials'), ('SSG', 'SS Graphics GFX Materials'), ('ABO', 'Aquas Brain Outro'), ('NEP', 'Nawab Editz Poster'), ('SST', 'SS Graphics Thumbnail'), ('NEG', 'Nawab Editz GFX Materials'), ('ABG', 'Aquas Brain GFX Materials'), ('AGB', 'Arpit Graphiz Banner'), ('SSI', 'SS Graphics Intro'), ('NEI', 'Nawab Editz Intro'), ('ABT', 'Aquas Brain Thumbnail'), ('ABR', 'Aquas Brain Render'), ('ABP', 'Aquas Brain Poster'), ('--', '------')], default='--', max_length=90),
        ),
    ]
