# Generated by Django 4.0.3 on 2022-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0003_subcategory_category_alter_ytpacks_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('AGG', 'Arpit Graphiz GFX Materials'), ('NEB', 'Nawab Editz Banner'), ('AGR', 'Arpit Graphiz Render'), ('SSI', 'SS Graphics Intro'), ('AGO', 'Arpit Graphiz Outro'), ('ABO', 'Aquas Brain Outro'), ('NEO', 'Nawab Editz Outro'), ('SSO', 'SS Graphics Outro'), ('SST', 'SS Graphics Thumbnail'), ('SSR', 'SS Graphics Render'), ('ABG', 'Aquas Brain GFX Materials'), ('ABP', 'Aquas Brain Poster'), ('ABB', 'Aquas Brain Banner'), ('AGT', 'Arpit Graphiz Thumbnail'), ('ABT', 'Aquas Brain Thumbnail'), ('NEG', 'Nawab Editz GFX Materials'), ('AGP', 'Arpit Graphiz Poster'), ('ABI', 'Aquas Brain Intro'), ('--', '------'), ('SSP', 'SS Graphics Poster'), ('SSG', 'SS Graphics GFX Materials'), ('SSB', 'SS Graphics Banner'), ('NER', 'Nawab Editz Render'), ('NET', 'Nawab Editz Thumbnail'), ('AGI', 'Arpit Graphiz Intro'), ('AGB', 'Arpit Graphiz Banner'), ('ABR', 'Aquas Brain Render'), ('NEP', 'Nawab Editz Poster'), ('NEI', 'Nawab Editz Intro')], default='--', max_length=90),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
