# Generated by Django 4.0.3 on 2022-04-21 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gfx', '0004_product_buy_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTPACKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(default='...')),
                ('image', models.ImageField(upload_to='GFXPack_Images/')),
                ('category', models.CharField(choices=[('AGI', 'Arpit Graphiz Intro'), ('SSR', 'SS Graphics Render'), ('ABO', 'Aquas Brain Outro'), ('AGO', 'Arpit Graphiz Outro'), ('NEG', 'Nawab Editz GFX Materials'), ('AGB', 'Arpit Graphiz Banner'), ('SST', 'SS Graphics Thumbnail'), ('AGT', 'Arpit Graphiz Thumbnail'), ('AGG', 'Arpit Graphiz GFX Materials'), ('ABI', 'Aquas Brain Intro'), ('AGP', 'Arpit Graphiz Poster'), ('NEO', 'Nawab Editz Outro'), ('SSG', 'SS Graphics GFX Materials'), ('SSP', 'SS Graphics Poster'), ('ABB', 'Aquas Brain Banner'), ('NEP', 'Nawab Editz Poster'), ('SSI', 'SS Graphics Intro'), ('ABP', 'Aquas Brain Poster'), ('AGR', 'Arpit Graphiz Render'), ('NEB', 'Nawab Editz Banner'), ('SSO', 'SS Graphics Outro'), ('NET', 'Nawab Editz Thumbnail'), ('NER', 'Nawab Editz Render'), ('NEI', 'Nawab Editz Intro'), ('ABG', 'Aquas Brain GFX Materials'), ('SSB', 'SS Graphics Banner'), ('ABR', 'Aquas Brain Render'), ('ABT', 'Aquas Brain Thumbnail'), ('--', '------')], default='--', max_length=90)),
                ('download_link', models.CharField(blank=True, max_length=999)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'title',
            },
        ),
    ]
