# Generated by Django 4.0.3 on 2022-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0004_remove_subcategory_category_remove_product_buy_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('NEG', 'Nawab Editz GFX Materials'), ('NET', 'Nawab Editz Thumbnail'), ('SST', 'SS Graphics Thumbnail'), ('AGG', 'Arpit Graphiz GFX Materials'), ('SSP', 'SS Graphics Poster'), ('NEI', 'Nawab Editz Intro'), ('AGP', 'Arpit Graphiz Poster'), ('NEB', 'Nawab Editz Banner'), ('SSI', 'SS Graphics Intro'), ('ABB', 'Aquas Brain Banner'), ('NER', 'Nawab Editz Render'), ('ABR', 'Aquas Brain Render'), ('ABO', 'Aquas Brain Outro'), ('NEO', 'Nawab Editz Outro'), ('SSB', 'SS Graphics Banner'), ('ABI', 'Aquas Brain Intro'), ('AGB', 'Arpit Graphiz Banner'), ('ABP', 'Aquas Brain Poster'), ('AGO', 'Arpit Graphiz Outro'), ('SSR', 'SS Graphics Render'), ('SSG', 'SS Graphics GFX Materials'), ('AGR', 'Arpit Graphiz Render'), ('SSO', 'SS Graphics Outro'), ('ABG', 'Aquas Brain GFX Materials'), ('AGT', 'Arpit Graphiz Thumbnail'), ('NEP', 'Nawab Editz Poster'), ('--', '------'), ('AGI', 'Arpit Graphiz Intro'), ('ABT', 'Aquas Brain Thumbnail')], default='--', max_length=90),
        ),
    ]
