# Generated by Django 4.0.3 on 2022-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0005_ytpacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ytpacks',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('NEO', 'Nawab Editz Outro'), ('NEI', 'Nawab Editz Intro'), ('--', '------'), ('ABO', 'Aquas Brain Outro'), ('SSO', 'SS Graphics Outro'), ('AGP', 'Arpit Graphiz Poster'), ('NEG', 'Nawab Editz GFX Materials'), ('AGR', 'Arpit Graphiz Render'), ('SSB', 'SS Graphics Banner'), ('SSI', 'SS Graphics Intro'), ('AGO', 'Arpit Graphiz Outro'), ('AGG', 'Arpit Graphiz GFX Materials'), ('ABG', 'Aquas Brain GFX Materials'), ('SSP', 'SS Graphics Poster'), ('SSG', 'SS Graphics GFX Materials'), ('SSR', 'SS Graphics Render'), ('SST', 'SS Graphics Thumbnail'), ('AGB', 'Arpit Graphiz Banner'), ('ABP', 'Aquas Brain Poster'), ('ABI', 'Aquas Brain Intro'), ('ABR', 'Aquas Brain Render'), ('NET', 'Nawab Editz Thumbnail'), ('NEB', 'Nawab Editz Banner'), ('NER', 'Nawab Editz Render'), ('ABT', 'Aquas Brain Thumbnail'), ('ABB', 'Aquas Brain Banner'), ('AGI', 'Arpit Graphiz Intro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('NEP', 'Nawab Editz Poster')], default='--', max_length=90),
        ),
    ]
