# Generated by Django 4.0.3 on 2022-04-27 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gfx', '0005_freepack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(default='Write description here....')),
                ('image', models.ImageField(upload_to='Paid_Images/')),
                ('download_link', models.CharField(blank=True, max_length=999)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sp', models.IntegerField(default=0)),
                ('dp', models.IntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfx.paidpackcat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'title',
            },
        ),
    ]
