# Generated by Django 4.0.3 on 2022-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0006_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('AGI', 'Arpit Graphiz Intro'), ('SSP', 'SS Graphics Poster'), ('SST', 'SS Graphics Thumbnail'), ('NEG', 'Nawab Editz GFX Materials'), ('AGG', 'Arpit Graphiz GFX Materials'), ('AGR', 'Arpit Graphiz Render'), ('NEI', 'Nawab Editz Intro'), ('AGP', 'Arpit Graphiz Poster'), ('SSR', 'SS Graphics Render'), ('ABP', 'Aquas Brain Poster'), ('ABT', 'Aquas Brain Thumbnail'), ('SSI', 'SS Graphics Intro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('NEO', 'Nawab Editz Outro'), ('ABG', 'Aquas Brain GFX Materials'), ('AGB', 'Arpit Graphiz Banner'), ('NEB', 'Nawab Editz Banner'), ('AGO', 'Arpit Graphiz Outro'), ('SSG', 'SS Graphics GFX Materials'), ('NEP', 'Nawab Editz Poster'), ('ABB', 'Aquas Brain Banner'), ('SSB', 'SS Graphics Banner'), ('ABR', 'Aquas Brain Render'), ('NER', 'Nawab Editz Render'), ('NET', 'Nawab Editz Thumbnail'), ('ABO', 'Aquas Brain Outro'), ('SSO', 'SS Graphics Outro'), ('ABI', 'Aquas Brain Intro'), ('--', '------')], default='--', max_length=90),
        ),
    ]
