# Generated by Django 4.0.3 on 2022-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0007_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('SSG', 'SS Graphics GFX Materials'), ('NEG', 'Nawab Editz GFX Materials'), ('--', '------'), ('NET', 'Nawab Editz Thumbnail'), ('AGG', 'Arpit Graphiz GFX Materials'), ('SSB', 'SS Graphics Banner'), ('AGT', 'Arpit Graphiz Thumbnail'), ('SSO', 'SS Graphics Outro'), ('NER', 'Nawab Editz Render'), ('SSI', 'SS Graphics Intro'), ('AGI', 'Arpit Graphiz Intro'), ('AGB', 'Arpit Graphiz Banner'), ('NEI', 'Nawab Editz Intro'), ('ABP', 'Aquas Brain Poster'), ('ABB', 'Aquas Brain Banner'), ('NEP', 'Nawab Editz Poster'), ('AGO', 'Arpit Graphiz Outro'), ('AGP', 'Arpit Graphiz Poster'), ('ABG', 'Aquas Brain GFX Materials'), ('SSR', 'SS Graphics Render'), ('ABT', 'Aquas Brain Thumbnail'), ('NEO', 'Nawab Editz Outro'), ('NEB', 'Nawab Editz Banner'), ('AGR', 'Arpit Graphiz Render'), ('SSP', 'SS Graphics Poster'), ('ABO', 'Aquas Brain Outro'), ('ABR', 'Aquas Brain Render'), ('SST', 'SS Graphics Thumbnail'), ('ABI', 'Aquas Brain Intro')], default='--', max_length=90),
        ),
    ]
