# Generated by Django 4.0.3 on 2022-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0007_remove_product_trending_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('AGO', 'Arpit Graphiz Outro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('AGP', 'Arpit Graphiz Poster'), ('AGI', 'Arpit Graphiz Intro'), ('NET', 'Nawab Editz Thumbnail'), ('ABO', 'Aquas Brain Outro'), ('--', '------'), ('SSR', 'SS Graphics Render'), ('SSI', 'SS Graphics Intro'), ('ABT', 'Aquas Brain Thumbnail'), ('SSB', 'SS Graphics Banner'), ('NEG', 'Nawab Editz GFX Materials'), ('AGB', 'Arpit Graphiz Banner'), ('SSG', 'SS Graphics GFX Materials'), ('NEB', 'Nawab Editz Banner'), ('NEI', 'Nawab Editz Intro'), ('SSO', 'SS Graphics Outro'), ('ABP', 'Aquas Brain Poster'), ('AGR', 'Arpit Graphiz Render'), ('AGG', 'Arpit Graphiz GFX Materials'), ('ABB', 'Aquas Brain Banner'), ('SSP', 'SS Graphics Poster'), ('NER', 'Nawab Editz Render'), ('ABR', 'Aquas Brain Render'), ('ABI', 'Aquas Brain Intro'), ('ABG', 'Aquas Brain GFX Materials'), ('NEP', 'Nawab Editz Poster'), ('SST', 'SS Graphics Thumbnail'), ('NEO', 'Nawab Editz Outro')], default='--', max_length=90),
        ),
    ]
