# Generated by Django 4.0.3 on 2022-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0008_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('SSB', 'SS Graphics Banner'), ('SSO', 'SS Graphics Outro'), ('AGT', 'Arpit Graphiz Thumbnail'), ('ABG', 'Aquas Brain GFX Materials'), ('--', '------'), ('AGR', 'Arpit Graphiz Render'), ('NEI', 'Nawab Editz Intro'), ('ABI', 'Aquas Brain Intro'), ('NEP', 'Nawab Editz Poster'), ('SSG', 'SS Graphics GFX Materials'), ('NEO', 'Nawab Editz Outro'), ('AGG', 'Arpit Graphiz GFX Materials'), ('NEB', 'Nawab Editz Banner'), ('NEG', 'Nawab Editz GFX Materials'), ('NER', 'Nawab Editz Render'), ('ABB', 'Aquas Brain Banner'), ('SST', 'SS Graphics Thumbnail'), ('ABT', 'Aquas Brain Thumbnail'), ('SSP', 'SS Graphics Poster'), ('SSI', 'SS Graphics Intro'), ('AGI', 'Arpit Graphiz Intro'), ('SSR', 'SS Graphics Render'), ('AGB', 'Arpit Graphiz Banner'), ('AGO', 'Arpit Graphiz Outro'), ('AGP', 'Arpit Graphiz Poster'), ('ABP', 'Aquas Brain Poster'), ('NET', 'Nawab Editz Thumbnail'), ('ABR', 'Aquas Brain Render'), ('ABO', 'Aquas Brain Outro')], default='--', max_length=90),
        ),
    ]
