# Generated by Django 4.0.3 on 2022-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0009_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('SSB', 'SS Graphics Banner'), ('ABR', 'Aquas Brain Render'), ('NEO', 'Nawab Editz Outro'), ('SSP', 'SS Graphics Poster'), ('ABG', 'Aquas Brain GFX Materials'), ('SST', 'SS Graphics Thumbnail'), ('SSG', 'SS Graphics GFX Materials'), ('NEG', 'Nawab Editz GFX Materials'), ('NEI', 'Nawab Editz Intro'), ('AGI', 'Arpit Graphiz Intro'), ('AGR', 'Arpit Graphiz Render'), ('AGT', 'Arpit Graphiz Thumbnail'), ('AGO', 'Arpit Graphiz Outro'), ('AGB', 'Arpit Graphiz Banner'), ('AGP', 'Arpit Graphiz Poster'), ('AGG', 'Arpit Graphiz GFX Materials'), ('ABP', 'Aquas Brain Poster'), ('SSR', 'SS Graphics Render'), ('ABI', 'Aquas Brain Intro'), ('NER', 'Nawab Editz Render'), ('ABB', 'Aquas Brain Banner'), ('SSO', 'SS Graphics Outro'), ('ABT', 'Aquas Brain Thumbnail'), ('NEB', 'Nawab Editz Banner'), ('NET', 'Nawab Editz Thumbnail'), ('SSI', 'SS Graphics Intro'), ('--', '------'), ('ABO', 'Aquas Brain Outro'), ('NEP', 'Nawab Editz Poster')], default='--', max_length=90),
        ),
    ]
