# Generated by Django 4.0.3 on 2022-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfx', '0010_alter_ytpacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytpacks',
            name='category',
            field=models.CharField(choices=[('ABO', 'Aquas Brain Outro'), ('AGR', 'Arpit Graphiz Render'), ('SSR', 'SS Graphics Render'), ('ABI', 'Aquas Brain Intro'), ('SSI', 'SS Graphics Intro'), ('AGB', 'Arpit Graphiz Banner'), ('AGI', 'Arpit Graphiz Intro'), ('ABT', 'Aquas Brain Thumbnail'), ('NEP', 'Nawab Editz Poster'), ('AGP', 'Arpit Graphiz Poster'), ('SSG', 'SS Graphics GFX Materials'), ('NEB', 'Nawab Editz Banner'), ('NEO', 'Nawab Editz Outro'), ('SSP', 'SS Graphics Poster'), ('ABR', 'Aquas Brain Render'), ('--', '------'), ('NEI', 'Nawab Editz Intro'), ('NER', 'Nawab Editz Render'), ('NEG', 'Nawab Editz GFX Materials'), ('SSO', 'SS Graphics Outro'), ('AGO', 'Arpit Graphiz Outro'), ('ABP', 'Aquas Brain Poster'), ('SST', 'SS Graphics Thumbnail'), ('NET', 'Nawab Editz Thumbnail'), ('AGG', 'Arpit Graphiz GFX Materials'), ('ABG', 'Aquas Brain GFX Materials'), ('SSB', 'SS Graphics Banner'), ('AGT', 'Arpit Graphiz Thumbnail'), ('ABB', 'Aquas Brain Banner')], default='--', max_length=90),
        ),
    ]
